# Generated by Django 2.0.4 on 2018-04-16 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vvt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datengruppen',
            name='datengruppe_anmerkung',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
