# Generated by Django 2.0.4 on 2018-04-16 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vvt', '0003_daten_datenverwendung'),
    ]

    operations = [
        migrations.CreateModel(
            name='Datenuebermittlung',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datenuebermittlung', models.CharField(max_length=200)),
                ('datenuebermittlung_rechtsgrundlagen', models.TextField()),
                ('datenuebermittlung_anmerkung', models.TextField()),
                ('daten', models.ManyToManyField(to='vvt.Daten')),
            ],
        ),
    ]
