# Generated by Django 2.0.4 on 2018-04-16 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vvt', '0004_datenuebermittlung'),
    ]

    operations = [
        migrations.AddField(
            model_name='datenuebermittlung',
            name='datenuebermittlung_zweck',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
