# Generated by Django 2.0.4 on 2018-04-16 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vvt', '0005_datenuebermittlung_datenuebermittlung_zweck'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datenverwendung',
            name='daten',
        ),
        migrations.DeleteModel(
            name='Datenverwendung',
        ),
    ]
