# Generated by Django 2.0.4 on 2018-05-25 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vvt', '0007_empfaenger'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rechtsgrundlage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bezeichnung', models.CharField(max_length=200)),
                ('text', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Verarbeitungstaetigkeit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('v_name', models.CharField(max_length=200)),
                ('verantwortlicher', models.CharField(max_length=100)),
                ('beschreibung', models.TextField()),
                ('zweck', models.TextField()),
                ('rechtsgrundlage', models.ManyToManyField(to='vvt.Rechtsgrundlage')),
            ],
        ),
        migrations.AddField(
            model_name='datenuebermittlung',
            name='rechtsgrundlagen',
            field=models.ManyToManyField(to='vvt.Rechtsgrundlage'),
        ),
        migrations.AddField(
            model_name='empfaenger',
            name='rechtsgrundlagen',
            field=models.ManyToManyField(to='vvt.Rechtsgrundlage'),
        ),
    ]
